### ISSUE TITLE
In decrypt I am getting error legacyMessage : Unsupported legacy version

### ISSUE THREAD

**Issue by ankitpolaris** [christophhagen/libsignal-protocol-swift#12]
Hi,

I've written a sample project using the library to encrypt and decrypt. While decrypting I am passing the message as below:
            let message = "Hi, This is First Encrypt Message".data(using: .utf8)
            let encryptedMessage = try cipher.encrypt(message!) 
            let encString = encryptedMessage.data.base64EncodedString()
Now at the decrypt
let encrData: Data = Data(base64Encoded: encString, options: .ignoreUnknownCharacters)!
let decryptedMessage = try cipher.decrypt(preKeySignalMessage: encrData)

I also tried out without the base64EncodedString. Then the code is as below:
            let message = "Hi, This is First Encrypt Message".data(using: .utf8)
            let encryptedMessage = try cipher.encrypt(message!) 
            let encString = encryptedMessage.data
Decrypt:
let decryptedMessage = try cipher.decrypt(preKeySignalMessage: encString)

I am getting the error : [WARNING] Unsupported legacy version: 0

Please help me out to resolve the issue.

**Comment by thibauddavid** [comment]
Hi, how'd you import it into your project ?

**Comment by thibauddavid** [comment]
You are using `encryptedMessage.data` instead of `encryptedMessage.message`

**Comment by ankitpolaris** [comment]
Yes, while decrypt I need to send it as a `message` instead of `preKeySignalMessage` and the `encryptedMessage` only without the need of `encString`. 
So, the correct way : 
`let decryptedMessage = try cipher.decrypt(message: encryptedMessage)`

The issue is resolved for me. Thank you.
